### ISSUE TITLE
Prepare picture set

### ISSUE THREAD

**Issue by horiaradu** [e-spres-oh/sherlock-ml#1]
Prepare a set of pictures with all the employees and annotate them.

**Comment by alecspopa** [comment]
We'll use the pictures for the triplet loss function https://www.coursera.org/learn/convolutional-neural-networks/lecture/HuUtN/triplet-loss

So I think we should name each picture in the following format:
`Alecs_Popa_1.jpg`, `Alecs_Popa_2.jpg`, `Horia_Radu_1.jpg`

and construct an excel file of the following format:

Anchor | Positive | Negative
------- | -------- | ---------
`Alecs_Popa_1.jpg` | `Alecs_Popa_2.jpg` | `Horia_Radu_1.jpg`

For the **Positive** column pick a picture that **is** the **Anchor** person.
For the **Negative** column pick a person that looks similar to the **Anchor** person. Don't use a person that is very different in gender, skin color, face structure etc...

**Comment by fulf** [comment]
I think a `.csv` of the following format would be more appropriate
||db_id||anchor||positive||negative
```
1,alecs_popa_1.jpg,alecs_popa_2.jpg,horia_radu_1.jpg
1,alecs_popa_1.jpg,alecs_popa_3.jpg,horia_radu_2.jpg
```

Seems a bit more flexible and size-friendly than a normal `.xlsx` file.

My recommendation would still be a database with two tables- `pictures` and `triplet-loss` because it would seem much more easier to add new people there via a web interface and re-run the ML algorithm to generate a new model when necessary. Though that might be a bit more complicated and better suited for V2.

**Comment by horiaradu** [comment]
I would go for the simplest thing in v1 :)

**Comment by alecspopa** [comment]
@fulf My suggestion was a excel file because it's way easier for @dmarkovits to work with and we can export a csv file from it easily. In Python I'll be needing a .csv file in the end so the choice is with @dmarkovits.
